# Site
repository: GlennPrince/glennprince.github.io
favicon: images/favicon.ico

# Personal info
name: Glenn Prince
title: Solution Architect
email: glenn@glennprince.com
website: www.glennprince.com

# Social links
twitter_username: Glenn_Prince
github_username:  GlennPrince
linkedin_username: glennprince

# About Section
about_title: About Me
# about_profile_image: images/profile.jpg
about_content: | # this will include new lines to allow paragraphs
  Hi, I'm Glenn. I am an experienced, pragmatic Solutions Architect that has helped organisations with transformative projects for the last few years. With diverse experience across development and infrastructure, I am passionate about learning new technologies and solving complex problems. I enjoy writing about my experiences and pretending to know how to code.

# Experience Section
# experience_title: Experience

# Education Section
# educaton_title: Education

# Projects Section
# projects_title: Projects

# More Section
# more_title: A Little More About Me
more_content: | # this will include new lines to allow paragraphs
  Alongside my interests in technology and software engineering some of my other interests and hobbies are:
   - Soccer
   - Gaming
   - Movies
   - Miniature Painting

# Footer
footer_show_references: true

# Build settings
remote_theme: sproogen/resume-theme

sass:
  sass_dir: _sass
  style: compressed

plugins:
 - jekyll-seo-tag
